fixed:
  dataset: qm9_pos
  log_path: './logs'

  use_wandb: False
  wandb_project: "experiment"
  wandb_name: "ppgn"

  downstream_model: PPGN  # change from GNN to PPGN
  only_downstream: False  # without the rewiring

  ppgn_configs:
    block_features: [400,400,400]
    depth_of_mlp: 2
    use_new_suffix: True

  sample_configs:
    separate: False
    directed: False
    sample_k: 20   # edge addition
    sample_k2: 5   # edge deletion
    candid_pool: 100
    ensemble: 1
    heuristic: longest_path  # TODO: all paths
    include_original_graph: True

  imle_configs:
    num_train_ensemble: 2 #3
    num_val_ensemble: 2 #3
    emb_hid_size: 64
    gnn_layer: 8 #8
    mlp_layer: 4
    batchnorm: True

  task_id: 0
  hid_size: 128
  lr: 1.e-3
  lr_decay:
    decay_rate: 0.5
    mode: 'min'
    patience: 5
  early_stop:
    patience: 15 #25
  reg: 0.
  num_convlayers: 4
  mlp_layers_intragraph: 0
  mlp_layers_intergraph: 2
  graph_pooling: max
  inter_graph_pooling: cat
  dropout: 0.2
  bn: True  # placeholder
  residual: True  # placeholder
  batch_size: 32
  min_epochs: 50
  max_epochs: 100
  data_path: './datasets'
  debug: True
  num_runs: 1
